**Q1. With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.**

In [1]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)
# [185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
#  182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
#  180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


**Given these daily weights, build an array with your average weight per weekend1.**

In [2]:
# solution

saturday = dailywts[5::7]
sunday = dailywts[6::7]

weekend_weight = saturday + sunday

## Now for the average of both days divide by 2

average_weekend_weight = weekend_weight/2
print(average_weekend_weight)

[183.9 182.5 181.1 179.7 178.3]


<h3>Q. Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

nola
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]

In [3]:
nola = np.arange(start=1, stop=65, step=2).reshape(4,-1)
## reshape(4,-1) 4 means 4 rows and -1 means automatic columns 
nola = nola[:, :-1]
## this removes tha last coloumn
print(nola)

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
